### ISSUE TITLE
Feedback - dependencies - no thanks

### ISSUE THREAD

**Issue by richard-browne** [scottoffen/grapevine#115]
Hello. I've found Grapevine V4. It looks great. Some feedback from one person.. I won't use Grapevine V5 because of the dependencies:

Grapeseed >= 5.0.0-rc.10)
Microsoft.Extensions.DependencyInjection >= 5.0.1
Microsoft.Extensions.DependencyInjection.Abstractions >= 5.0.0
Microsoft.Extensions.Logging.Abstractions >= 5.0.0
Microsoft.Extensions.Logging.Console >= 5.0.0

I don't want a nuget package which pulls in 5 others, then potentially more transitive dependencies. No thanks. Please just give me a nuget package with no dependencies like V4.

**Comment by scottoffen** [comment]
Then I would recommend that you continue to use Grapevine v4, especially if you don't know what those dependencies are for in Grapevine 5. I am not going to waste my time writing, documenting and maintaining my own logging and dependency injection implementations just to avoid pulling in some standard .NET libraries.

I have separated the parts of Grapevine that do not depend on `HttpListener` into the Grapeseed package. This does not change anything for Grapevine, but will allow others to re-use those parts to build implementations that do not rely on `HttpListener`, if they so chose.
