### ISSUE TITLE
[bug] RestServer not working on localhost

### ISSUE THREAD

**Issue by hadi73ebrahimi** [scottoffen/grapevine#130]
I have built a server in the past that works on localhost, but today after pasting a sample code of it i could get it work on in new project.
here is my code:

```
ServerSettings setting;
        RestServer server;
        public Core()
        {
            setting = new ServerSettings();
            setting.Port = "50055";
            setting.Host = "*";
            Start();
        }
        private void Start()
        {
            using (server = new RestServer(setting))
            {
                server.LogToConsole(Grapevine.Interfaces.Shared.LogLevel.Debug);
                server.Start();
            }

        }
```

this code works on my previous app(localhost) but not with new app. i have no idea.

**Comment by scottoffen** [comment]
When changing major versions (from 4 to 5, for example), you should expect there to be some breaking changes. While I know there isn't a lot of documentation around Grapevine, but there is some, and there is [this page](https://scottoffen.github.io/grapevine/docs/).

Try this:

```csharp
using (var server = RestServerBuilder.UseDefaults().Build())
{
    server.Prefixes.Add("http://*:50055");
    server.Run();
}
```

**Comment by defenderjim** [comment]
`server.Prefixes.Add("http://*:50055");`
    Yeah, uh, that line of code throws an exception for me.
    _'Only Uri prefixes ending in '/' are allowed. (Parameter 'uriPrefix')'_
