### ISSUE TITLE
Prefixes.Add throw exception

### ISSUE THREAD

**Issue by defenderjim** [scottoffen/grapevine#132]
```csharp
server.Prefixes.Add("http://*:50055");
```

That line of code throws an exception for me.
    _'Only Uri prefixes ending in '/' are allowed. (Parameter 'uriPrefix')'_
    Running 5.0.0-rc

**Comment by scottoffen** [comment]
That is correct. Change that line according to the error message provide and it will work.

```csharp
server.Prefixes.Add("http://*:50055/");
```
