### ISSUE TITLE
Handling multiple GET request parameters

### ISSUE THREAD

**Issue by chinnuu05** [scottoffen/grapevine#143]
The documentation leaves this really unclear

Say I have a route like this
`[RestRoute("Get", "/updatetasks/{blockID}/{isChecked}")]`

What's the proper way to hit this route?? The below did not work.
`localhost/updatetasks/myblockid/false`

I've tried so many variations and none work. Using ?blockID params don't work either...

Please advise.

**Comment by scottoffen** [comment]
This code works just fine for me:

```csharp
[RestRoute("Get", "/updatetasks/{blockID}/{isChecked}")]
public async Task ShowValuesFromRoute(IHttpContext context)
{
    var blockID = context.Request.PathParameters["blockID"];
    var isChecked = context.Request.PathParameters["isChecked"];

     await context.Response.SendResponseAsync(HttpStatusCode.Ok, $"{blockID}:{isChecked}");
}
```

You might just be missing the port number in your url.  By default, Grapevine will listen on port 1234. So, if you didn't change that, you should be hitting `localhost:1234/updatetasks/myblockid/false`.
