### ISSUE TITLE
Grapevine v5 HTTPS support when run inside a .NET Linux container?

### ISSUE THREAD

**Issue by dwrightpulse** [scottoffen/grapevine#23]
We have used Grapevine v4 for awhile and recently found an issue whereby our applications don't support HTTPS connections when they are run as .NET core apps in Linux containers.  We have attributed this to  https://github.com/dotnet/runtime/issues/32721 (ignore the title of the post).

Can anyone tell me whether this is resolved in v5? And if so, how is Grapevine told which certificate to use (netsh.exe not available on a Linux container host)?

Thanks in anticipation!

**Comment by scottoffen** [comment]
This is not resolved in any of the prerelease versions of Grapevine thus far. I'll leave this ticket here for now, and we can decide later how to approach this.

**Comment by dwrightpulse** [comment]
Thanks @scottoffen...  Confirming then that this is functionality that you would look add to Grapevine in the future then?

**Comment by scottoffen** [comment]
I can't confirm that right now, I don't know enough about what it would take to add that functionality. But I'm willing to put it on the roadmap and consider it. If it can be done in a way that is clean, maintainable and stable, I think it would a good feature to have.

**Comment by scottoffen** [comment]
I've started [a discussion here](https://github.com/scottoffen/grapevine/discussions/26) on this topic. Hopefully we can get some input from the broader community. If, from that discussion, a course of action is decided to make an update to Grapevine, we'll open a new ticket for that.
