### ISSUE TITLE
Cannot reach the RestServer other than localhost.

### ISSUE THREAD

**Issue by ozgurkaya111** [scottoffen/Grapevine#35]
Hello ,
I am using VS2012 and Grapevine 3.0.4  , when i use the Grapevine same machine with localhost 
hostname , everything works well.
If I want to reach from other PC with client ,  Server could not be start listening with hostname ip address or  Computername 

If i try server pc set hostname to localhost , it starts listening  but when reached from other PC with IP or name server returns bad request 400 

Is it something wrong with my code or library.

My Server code is
    public class embeddedHTTP //
        {

        private RESTServer Server;

        public void ServerStart()
        {

            try
            {

                Server = new RESTServer();
                Server.Port =  GlobalVars.HttpHostPort;
                Server.Host = GlobalVars.HttpHostAdress; // THIS ONLY WORKS FOR LOCALHOST
                Server.MaxThreads = 20;
                Server.Start();
                

                while (Server.IsListening)
                {
                    Thread.Sleep(GlobalVars.HttpHostRespTime);
                }
            }

            catch (Exception ex)
            {
                messenger.logque("embedded HTTP server not started, Error ID : 52", 3, null);

            }

        }

        public void ServerStop()
        {

            
            Server.Stop();
        }

      
        public sealed class MyResource : RESTResource
        {

            //d+$^  [a-zA-Z]+
            [RESTRoute(Method = Grapevine.HttpMethod.GET, PathInfo = @"/")] 
            public void HandleFooRequests(HttpListenerContext context)
            {
            
           //     String RawuR = context.Request.RawUrl;
                String URL = Convert.ToString(context.Request.Url);
                String ResultXML = brain.HTTPCMD(URL);          
                this.SendTextResponse(context, ResultXML);

            }

         }

        }

**Comment by scottoffen** [comment]
From the [**Limitations** section of the README.md](https://github.com/scottoffen/Grapevine/blob/master/README.md#limitations):

>You will likely be required to [open a port in your firewall](http://www.lmgtfy.com/?q=how+to+open+a+port+on+windows) for remote computers to be able to send requests to your application. Grapevine will not [automatically](http://msdn.microsoft.com/en-us/library/aa366418%28VS.85%29.aspx) do that for you.  You might want to do that during the [installation of your application](http://www.codeproject.com/Articles/14906/Open-Windows-Firewall-During-Installation).

If you can access the server using `localhost`, but not from other computes, this is your problem. Grapevine does not resolve this for you.

**Comment by ozgurkaya111** [comment]
​I am sorry , I did find solution, but still not working. As you said , the
problem is my computer firewall .

Thanks for your kind reply .
and thanks for Grapevine, it  is a great tool for us ,
​
Have a nice day .

*Özgür KAYA*

http://about.me/ozgurkaya111


2015-10-08 0:31 GMT+03:00 Scott Offen <notifications@github.com>:

**Comment by scottoffen** [comment]
I'm glad you've found it useful!

**Comment by anishpsla** [comment]
I also have the same problem. netstat -a shows the server is listening on 0.0.0.0:8080 but only accessible through http://localhost:8080 even http://127.0.0.1:8080 not working. Also even after disabling firewall, I can't access the server on another computer

**Comment by jimmyland** [comment]
Maybe try the following:

When you create the new RESTServer(...), the first argument (hostname) can be "*"

Of course check the firewall settings and ensure you've opened the port you're running the server on

Either run the server as admin, or open a terminal as admin and run "netsh http add urlacl url=http://*:1234/ user=Everyone"  (where 1234 should be whatever port you're running on)

**Comment by MiaoDX** [comment]
Just a small note on this, in case someone needs one simple example (4.x version):

``` java

using (var server = new RestServer())
{
    server.Host = "*";
    server.Port = "1024";

    server.LogToConsole().Start();
    Console.ReadLine();
    server.Stop();
}
```

However, run this in VS directly will encouter errors:

``` vi
Exception thrown: 'Grapevine.Exceptions.Server.UnableToStartHostException' in Grapevine.dll
An unhandled exception of type 'Grapevine.Exceptions.Server.UnableToStartHostException' occurred in Grapevine.dll
Additional information: An error occured when trying to start the Grapevine.Server.RestServer
```

The simplest and cleanest way (in my opinion) is do as @jimmyland pointed out, run it in **command line** but **with admin privileges**.
