### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ertan2002** [scottoffen/grapevine#63]
Hi all

The app that I am developing, is using 50% of my CPU (virtual machine) and the version that I use is V 5.0.0 rc.7 and I reduced the version to rc.6, then the cpu usage becomes 0% :) 

So there is an issue in the latest pre-release (rc.7). Could you please check the problem?

I see that, a similar problem happened here 
https://github.com/scottoffen/grapevine-legacy/issues/138

Anyway I am using rc.6 for now and there is no problem in my side. Just want to mention that the rc.7 uses high cpu resource!

thanks

**Comment by scottoffen** [comment]
Can you provide additional detail and sample code on this? I am unable to reproduce this issue.

**Comment by scottoffen** [comment]
Duplicate of #41
