### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by seikosantana** [scottoffen/grapevine#66]
Do we have WebSocket support in Grapevine 5? Or server sent events? If no, are they planned?

**Comment by scottoffen** [comment]
Please move this question over to the [discussion page](https://github.com/scottoffen/grapevine/discussions) for further discussion. Per the [contributing guidelines](https://github.com/scottoffen/grapevine/blob/737580560372f5524c44315970310f38c2748f25/CONTRIBUTING.md#issue-management):

> GitHub issues are reserved for things that can be fixed, added, resolved, or implemented. Here are some guidelines we use in order to manage incoming issues in the most efficient way.

Thanks!
